import type { TradieUser } from './type';

export const tradies: TradieUser[] = [
    {
        name: "Dave Johnson",
        description: "Experienced electrician, specializes in household wiring.",
        jobRole: "Electrician",
        color: "red",
    },
    {
        name: "Sarah Brown",
        description: "Modern architect with a flair for innovative designs.",
        jobRole: "Architect",
        color: "blue",
    },
    {
        name: "Bob Smith",
        description: "Renovations and remodeling expert.",
        jobRole: "Builder",
        color: "green",
    },
    {
        name: "Alison Green",
        description: "Plumbing installations and repair specialist.",
        jobRole: "Plumber",
        color: "purple",
    },
    {
        name: "Steve White",
        description: "Professional painter for interior and exterior projects.",
        jobRole: "Painter",
        color: "yellow",
    },
    {
        name: "Liam Taylor",
        description: "Carpenter skilled in detailed finishing work.",
        jobRole: "Carpenter",
        color: "orange",
    },
    {
        name: "Grace Hall",
        description: "Civil engineer focused on sustainable building.",
        jobRole: "Civil Engineer",
        color: "lime",
    },
    {
        name: "Tom Clark",
        description: "Efficient handyman for quick fixes and repairs.",
        jobRole: "Handyman",
        color: "brown",
    },
    {
        name: "Jessica Martinez",
        description: "Landscaper transforming gardens into beautiful spaces.",
        jobRole: "Landscaper",
        color: "pink",
    },
    {
        name: "Mike Wilson",
        description: "Project manager for complex commercial constructions.",
        jobRole: "Project Manager",
        color: "grey",
    },
    {
        name: "Samantha Davis",
        description: "HVAC expert, specializes in energy-efficient solutions.",
        jobRole: "HVAC Technician",
        color: "aqua",
    },
    {
        name: "Carlos Robinson",
        description: "High-end kitchen installation expert.",
        jobRole: "Kitchen Fitter",
        color: "maroon",
    },
];

export const tradieChats: string[] = [
    "Oi mate, how’s the hammer hangin'?",
    "Just another day in paradise, cobber. How's the build goin'?",
    "Strewth, it’s hotter than a shearer’s armpit today!",
    "Pass me that left-handed screwdriver... Yeah, the good ol’ shifter!",
    "Ever tried hammering in screws? It’s a game changer.",
    "This saw’s as blunt as a bank manager, mate.",
    "I reckon we finish up early and grab a cold one at the pub.",
    "That's not how you hold a drill, mate. Imagine it's a cold beer!",
    "You call that a nail? That’s a tack in disguise!",
    "Mate, your toolbox is messier than my teenager's room.",
    "Let's knock off and hit the servo for a meat pie, I'm starvin'.",
    "Watch out! Nearly hit my thumb. That would’ve been a sickie tomorrow!",
    "You’ve got more chance of bending a spoon telepathically than bending that pipe.",
    "That paint color is brighter than my future.",
    "Crikey, you actually showed up on time today!",
    "Bet my dog could’ve dug that hole faster than you!",
    "How many tradies does it take to change a lightbulb? None, that’s an electrician’s job.",
    "She’ll be right, just slap some duct tape on it.",
    "Mate, did you bring the snags? It's your shout for the barbie this arvo.",
    "I told the apprentice to get me a long weight, and he’s still gone!",
    "Look at that, cleaner than a whistle!",
    "Gotta love it when the boss says it's an easy job but it's not even close.",
    "Righto, who's turn is it to shout the Tim Tams?",
    "My back’s giving me more grief than the missus!",
    "Yeah, nah, she’s pretty dodgy. Gonna need a full redo.",
    "If that’s plumb, I’m the Queen of England.",
    "Good job, mate. That’s straighter than a die.",
    "Gotta be careful or you’ll end up in the drink!",
    "Oi, toss me that frothy, would ya?",
    "These flies are friendlier than the taxman at a barbecue!",
    "Let's not make a meal of it. In and out.",
    "Put a snag on the barbie, it’s almost knock-off time.",
    "That mix is drier than a dead dingo’s donger.",
    "We’ll cross that bridge when we come to it... if it hasn’t fallen down yet.",
    "This old Ute will make it to the moon before we finish here.",
    "I’m as busy as a one-legged man in a butt-kicking contest!",
    "Keep your hair on, I’m on it like a car bonnet.",
    "Not my circus, not my monkeys... Wait, wrong job!",
    "That level’s about as useful as an ashtray on a motorbike.",
    "Running late? Throw a snag on for me, would ya?",
    "Yeah, she’s a bit rough around the edges but she’ll hold.",
    "Why do we always end up with the jobs that are up the creek?",
    "If I had a dollar for every time I heard 'just one more fix', I’d be retired.",
    "Fancy a game of ‘spot the apprentice’ today?",
    "Watch this, mate... it’s gonna be a piece of cake.",
    "Don’t tell the boss, but I reckon I fixed it better.",
    "What’s the difference between a carpenter and a politician? A carpenter can actually build stuff.",
    "This wiring’s older than my granddad!",
    "Grab the esky, let’s have lunch.",
    "These plans look like they were drawn by my five-year-old.",
    "Last one to the van is buying morning tea!",
    "Ever seen a sparkie use a shovel? Me neither.",
    "Hey, careful with that, it’s not a toy!",
    "Got enough screws there, mate, or planning to build a spaceship?",
    "This job’s been going on longer than a cricket match.",
    "A cold beer after a long day... now that’s talking sense.",
];
